### ISSUE TITLE
docker-compose example

### ISSUE THREAD

**Issue by jjjuk** [sigoden/dufs#129]
**Problem**

How should I configure dufs in docker-compose file? I have this config:
```yaml
  upload:
    image: sigoden/dufs:latest
    restart: always
    volumes:
      - type: volume
        source: files
        target: /data
    ports:
      - 5000:5000
    command: dufs -A -a /@admin:pass@* && dufs data
    networks:
      internal:
        aliases:
          - upload
```

But it starts up with an error:

**Log**
```log
azapi-upload-1    | error: Path `dufs` doesn't exist
azapi-upload-1    | error: Path `dufs` doesn't exist
azapi-upload-1    | error: Path `dufs` doesn't exist
azapi-upload-1    | error: Path `dufs` doesn't exist
azapi-upload-1    | error: Path `dufs` doesn't exist
azapi-upload-1    | error: Path `dufs` doesn't exist
azapi-upload-1    | error: Path `dufs` doesn't exist
azapi-upload-1    | error: Path `dufs` doesn't exist
azapi-upload-1    | error: Path `dufs` doesn't exist
azapi-upload-1    | error: Path `dufs` doesn't exist
azapi-upload-1    | error: Path `dufs` doesn't exist
azapi-upload-1    | error: Path `dufs` doesn't exist
```
Also, it would be great if you add docker-compose usage example to Readme)

Thank you!

**Comment by sigoden** [comment]
This docker image behaves like a dufs binary. 

 `dufs  -A -a '/@admin:pass@*'`  in docker-compose will be

```
  dufs:
    image: sigoden/dufs
    ports:
    - 5000:5000
    volumes:
    - .:/data
    command: /data -A -a '/@admin:pass@*'
```
Just put dufs args  to docker-compose command
