### ISSUE TITLE
Add PUID/PGID ENV var support in Dockerfile

### ISSUE THREAD

**Issue by NERVEbing** [sigoden/dufs#149]
## Specific Demand

Add PUID/PGID ENV var support in Dockerfile.

## Implement Suggestion

If the process is running under root, all files and directories created during the container's lifespan will be owned by root, thus becoming inaccessible by users, this is important for NAS.

Thank you.

**Comment by sigoden** [comment]
use `user` to specific uid:pid of running process.

```
docker run -u $(id -u):$(id -g) -v `pwd`:/data -p 5000:5000 --rm -it sigoden/dufs /data -A
```

```
version: '3'
services:
  dufs:
    image: sigoden/dufs
    ports:
    - 5000:5000
    volumes:
    - .:/data
    command: /data -A
    user: "1000:1000"
```
