### ISSUE TITLE
required events notification 

### ISSUE THREAD

**Issue by fj0r** [sigoden/dufs#287]
## Specific Demand

Allows webhook notifications to be sent when files are created, modified, and deleted (optional indexing, download event notifications)

Easy to integrate with other systems, such as CI/CD

## Implement Suggestion
event data like this:
```
{
    type:  update|modify|delete|index|download
    datetime: <now>
    path: path/to
    file:  example
    ext: txt|json|....
    is_dir: false
    size: ...
    client_ip: 1.2.3.4
    ua: ....
}
```

**Comment by fj0r** [comment]
It is best to customize the notification format and support filtering, such as simulating github events

```yaml
notification:
  - events:
        - update
        - modify
        - delete
    prefix:
        - /a/b/c
        - /d/e
    template:  commit.json
  - events:
        - update
    prefix:
        - /
    template:  default.json
```

```json
# commit.json
{
    "type":  "commit",
    "message": "dufs {{client_ip}} commit {{action}} {{path}}/{{file}}.{{ext}}"
}
# default.json
{
    "type":  "{{type}}",
    "datetime": "{{datetime}}",
    ....
}
```
