### ISSUE TITLE
When using webdav, unauthorized directories are still visible.

### ISSUE THREAD

**Issue by EdenHell** [sigoden/dufs#338]
**Problem**

The unauthorized directory can still be displayed in Kodi, although the files inside cannot be viewed. However, I do not want it to be shown.

![无标题](https://github.com/sigoden/dufs/assets/5779655/7eb2a900-b1b2-42c6-935f-54321afb5cc3)

The expected effect is achieved when browsing in a web browser.

![image](https://github.com/sigoden/dufs/assets/5779655/8158a490-aa39-4b02-8ced-400712121adb)

**Conf**

```yml
serve-path: '/root'
port: 19999
auth:
  - admin:dummy_pwd@/:rw
  - user:fake_pwd@/videos/Movie,/videos/TV series
allow-all: false
allow-upload: true
allow-delete: false
allow-search: true
allow-archive: true
enable-cors: true
render-try-index: true
```

**Environment:**
 - Dufs version: docker [v0.38.0](https://hub.docker.com/layers/sigoden/dufs/v0.38.0/images/sha256-5f64acd74ce48cf92f28ec7f138d2f8aeedfaa8972e9786d3fe10dbb6e3a2be1?context=explore)
 - Browser/Webdav Info:  kodi
 - OS Info:  Android
