### ISSUE TITLE
Icons are vertical down the page

### ISSUE THREAD

**Issue by loricah** [sigoden/dufs#418]
**Problem**

When loading up dufs using the docker container, all of the icons are placed vertically down the left-hand side of the page.

**Configuration**

compose.dufs.yaml:

```
services:
  dufs:
    image: sigoden/dufs:latest
    container_name: dufs
    volumes:
      - .:/data
    command: /data -A -p 80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dufs.rule=Host(`${SERVER_DOMAIN:-localhost}`) && PathPrefix(`/files`)"
      - "traefik.http.routers.dufs.service=dufs”
      - "traefik.http.routers.dufs.entrypoints=websecure"
      - "traefik.http.services.dufs.loadbalancer.server.port=80"
    networks:
      - internal
    restart: unless-stopped
```

**Log**

```
dufs-1        | Listening on:
dufs-1        |    http://127.0.0.1:80/
dufs-1        |    http://172.18.0.2:80/
dufs-1        |
dufs-1        | 2024-07-19T19:50:48Z INFO - 172.18.0.3 “GET /files/“ 200
```

**Environment:**
 - Dufs version: latest docker container
 - Browser/Webdav info: Firefox/Chrome
 - OS info: Ubuntu 20.04.6 LTS
 - Proxy server:  traefik
