### ISSUE TITLE
Weird permission issue

### ISSUE THREAD

**Issue by fucksophie** [sigoden/dufs#424]
**Problem**

1. Create a /data folder
2. Create "user", "user1" and "public" folders in that directory
3. Run the docker compose below

Configuration works correctly for user and user1, they can access their own directories and public. 
But you cannot view the public directory anymously, which is what I'm trying to achieve.

**Configuration**

```
version: '3.3'
services:
    run:
        volumes:
            - '/***YOUR DIRECTORY***/data'
        ports:
            - '127.0.0.1:8000:8000'
        image: sigoden/dufs
        command: /data -A -p 8000 -a "user:pass..@/user:rw,/public:rw" -a "user1:pass@/user1:rw,/public:rw" -a "@/public:r"
```

**Log**

run-1  | 2024-07-26T17:25:28Z INFO - 172.28.0.1 "GET /" 200

**Environment:**
 - Dufs version: Dufs 0.41.0
 - Browser/Webdav info: Vivaldi
 - OS info: Linux AMD64
 - Proxy server: Caddy
