### ISSUE TITLE
"allow-all=true" in config.yaml doesn't work

### ISSUE THREAD

**Issue by lyxichigoichie** [sigoden/dufs#479]
**Problem**

While I set `allow-all-true` in the `config.yaml` and run
```bash
./dufs --config config.yaml
```
It seems it doesn't work since the upload, new file, new folder icon do not appear on the webpage
**Configuration**
config.yaml
```yaml
serve-path: '/mnt/e'
bind: 0.0.0.0
port: 5000
#path-prefix: /dufs
hidden:
  - tmp
  - '*.log'
  - '*.lock'
auth:
  - admin:admin@/:rw
  - user:pass@/src:rw,/share
  - '@/'  # According to the YAML spec, quoting is required.
allow-all: true
#allow-upload: true
#allow-delete: true
#allow-search: true
#allow-symlink: true
#allow-archive: true
enable-cors: true
render-index: true
render-try-index: true
render-spa: true
#assets: ./data
log-format: '$remote_addr "$request" $status $http_user_agent'
log-file: ./dufs.log
compress: low
#tls-cert: tests/data/cert.pem
#tls-key: tests/data/key_pkcs1.pem
```

**Screenshots/Media**
![0b5cf0bf0b365f9b7a7c386791b58f7](https://github.com/user-attachments/assets/0f0e6193-c87a-487a-854e-8a096f30e760)

**Environment Information**
 - Dufs version: v0.43.0
 - Browser/Webdav info: chrome
 - OS info: ubuntu20.04 in WSL 2.0, win10
