### ISSUE TITLE
Support different operations for different path

### ISSUE THREAD

**Issue by Zieng** [sigoden/dufs#484]
## Specific Demand
We can allow specific operations for the whole path, however it seems we can not usedifferent operations for different path, eg:
```
version: '3'
services:
  dufs:
    image: sigoden/dufs
    container_name: dufs
    ports:
    - 5032:5000
    volumes:
    - ./data:/data
    command: /data/a -A /data/b --allow-upload
```
