### ISSUE TITLE
Unable to upload files, when accessing using domain names in a local area network environment

### ISSUE THREAD

**Issue by MingfuYAN** [sigoden/dufs#523]
**Problem**

When accessing via a domain name in the local area network (LAN), file uploads fail, while downloads work normally. Please note that my domain name has been resolved to the LAN IP address. Uploads function correctly when accessing directly using the LAN IP address.

**Configuration**

```yml
services:
  dufs-share:
    image: sigoden/dufs:latest
    container_name: dufs
    restart: unless-stopped
    volumes:
      - /data0/mfyan/docker/dufs/files:/share
    ports:
      - "50000:5000"
    command: /share -A -a username:password@/:rw --enable-cors
```

**Log**

**Screenshots/Media**

<img width="1918" alt="image" src="https://github.com/user-attachments/assets/343b68d4-72c3-4dc5-935a-67e972f31734" />

**Environment Information**
 - Dufs version: `v0.43.0`
 - Browser/Webdav info: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36`
 - OS info: `Linux amax 5.15.0-126-generic #136~20.04.1-Ubuntu SMP Thu Nov 14 16:38:05 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`
 - Proxy server (if any):
